config/routes.rb
Rails.application.routes.draw do
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :charges
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @success_charges = Charge.where(paid: true , refunded: false)
    @failed_charges = Charge.where(paid: false , refunded: false)
    @disputed_charges = Charge.where(paid: true , refunded: true)
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def charge_params
      params.fetch(:charge, {})
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_with(model: charge, local: true) do |form| %>
  <% if charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
        <% charge.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Failed Charges</h1>
<table id="failed_table" class="table table-hover">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Paid</th>
      <th>Refunded</th>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody  style="color: #fff">
    <% @failed_charges.each_with_index do |charge, index| %>
      <tr class="failed_tr" style="background-color: #FF0000">
        <td><%= index+1 %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer.first_name+ " " + charge.customer.last_name %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Disputed Charges</h1>
<table id="disputed_table" class="table table-hover">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Paid</th>
      <th>Refunded</th>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody  style="color: #fff">
    <% @disputed_charges.each_with_index do |charge, index| %>
      <tr class="disputed_tr" style="background-color: #FF5400">
        <td><%= index+1 %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer.first_name+ " " + charge.customer.last_name %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Successful Charges</h1>
<table id="success_table" class="table table-hover">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Paid</th>
      <th>Refunded</th>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody  style="color: #fff">
    <% @success_charges.each_with_index do |charge, index| %>
      <tr class="success_tr" style="background-color: #316e41">
        <td><%= index+1 %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer.first_name + " " + charge.customer.last_name %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%#= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>